package Font::Bitmap::BDF::AdobeGlyphListForNewFonts;
use warnings;
use strict;

use vars ('%aglfnByName', '%aglfnByCodepoint',
	  '%aglfnByNameArray', '%aglfnByCodepointArray');

use base 'Exporter';

BEGIN {
    our @EXPORT_OK   = ('adobeGlyphName', 'adobeGlyphCodepoint');
    our %EXPORT_TAGS = (all => ['adobeGlyphName', 'adobeGlyphCodepoint']);
}

INIT {
    add(0x0041, 'A', 'LATIN CAPITAL LETTER A');
    add(0x00C6, 'AE', 'LATIN CAPITAL LETTER AE');
    add(0x01FC, 'AEacute', 'LATIN CAPITAL LETTER AE WITH ACUTE');
    add(0x00C1, 'Aacute', 'LATIN CAPITAL LETTER A WITH ACUTE');
    add(0x0102, 'Abreve', 'LATIN CAPITAL LETTER A WITH BREVE');
    add(0x00C2, 'Acircumflex', 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX');
    add(0x00C4, 'Adieresis', 'LATIN CAPITAL LETTER A WITH DIAERESIS');
    add(0x00C0, 'Agrave', 'LATIN CAPITAL LETTER A WITH GRAVE');
    add(0x0391, 'Alpha', 'GREEK CAPITAL LETTER ALPHA');
    add(0x0386, 'Alphatonos', 'GREEK CAPITAL LETTER ALPHA WITH TONOS');
    add(0x0100, 'Amacron', 'LATIN CAPITAL LETTER A WITH MACRON');
    add(0x0104, 'Aogonek', 'LATIN CAPITAL LETTER A WITH OGONEK');
    add(0x00C5, 'Aring', 'LATIN CAPITAL LETTER A WITH RING ABOVE');
    add(0x01FA, 'Aringacute', 'LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE');
    add(0x00C3, 'Atilde', 'LATIN CAPITAL LETTER A WITH TILDE');
    add(0x0042, 'B', 'LATIN CAPITAL LETTER B');
    add(0x0392, 'Beta', 'GREEK CAPITAL LETTER BETA');
    add(0x0043, 'C', 'LATIN CAPITAL LETTER C');
    add(0x0106, 'Cacute', 'LATIN CAPITAL LETTER C WITH ACUTE');
    add(0x010C, 'Ccaron', 'LATIN CAPITAL LETTER C WITH CARON');
    add(0x00C7, 'Ccedilla', 'LATIN CAPITAL LETTER C WITH CEDILLA');
    add(0x0108, 'Ccircumflex', 'LATIN CAPITAL LETTER C WITH CIRCUMFLEX');
    add(0x010A, 'Cdotaccent', 'LATIN CAPITAL LETTER C WITH DOT ABOVE');
    add(0x03A7, 'Chi', 'GREEK CAPITAL LETTER CHI');
    add(0x0044, 'D', 'LATIN CAPITAL LETTER D');
    add(0x010E, 'Dcaron', 'LATIN CAPITAL LETTER D WITH CARON');
    add(0x0110, 'Dcroat', 'LATIN CAPITAL LETTER D WITH STROKE');
    add(0x2206, 'Delta', 'INCREMENT');
    add(0x0045, 'E', 'LATIN CAPITAL LETTER E');
    add(0x00C9, 'Eacute', 'LATIN CAPITAL LETTER E WITH ACUTE');
    add(0x0114, 'Ebreve', 'LATIN CAPITAL LETTER E WITH BREVE');
    add(0x011A, 'Ecaron', 'LATIN CAPITAL LETTER E WITH CARON');
    add(0x00CA, 'Ecircumflex', 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX');
    add(0x00CB, 'Edieresis', 'LATIN CAPITAL LETTER E WITH DIAERESIS');
    add(0x0116, 'Edotaccent', 'LATIN CAPITAL LETTER E WITH DOT ABOVE');
    add(0x00C8, 'Egrave', 'LATIN CAPITAL LETTER E WITH GRAVE');
    add(0x0112, 'Emacron', 'LATIN CAPITAL LETTER E WITH MACRON');
    add(0x014A, 'Eng', 'LATIN CAPITAL LETTER ENG');
    add(0x0118, 'Eogonek', 'LATIN CAPITAL LETTER E WITH OGONEK');
    add(0x0395, 'Epsilon', 'GREEK CAPITAL LETTER EPSILON');
    add(0x0388, 'Epsilontonos', 'GREEK CAPITAL LETTER EPSILON WITH TONOS');
    add(0x0397, 'Eta', 'GREEK CAPITAL LETTER ETA');
    add(0x0389, 'Etatonos', 'GREEK CAPITAL LETTER ETA WITH TONOS');
    add(0x00D0, 'Eth', 'LATIN CAPITAL LETTER ETH');
    add(0x20AC, 'Euro', 'EURO SIGN');
    add(0x0046, 'F', 'LATIN CAPITAL LETTER F');
    add(0x0047, 'G', 'LATIN CAPITAL LETTER G');
    add(0x0393, 'Gamma', 'GREEK CAPITAL LETTER GAMMA');
    add(0x011E, 'Gbreve', 'LATIN CAPITAL LETTER G WITH BREVE');
    add(0x01E6, 'Gcaron', 'LATIN CAPITAL LETTER G WITH CARON');
    add(0x011C, 'Gcircumflex', 'LATIN CAPITAL LETTER G WITH CIRCUMFLEX');
    add(0x0120, 'Gdotaccent', 'LATIN CAPITAL LETTER G WITH DOT ABOVE');
    add(0x0048, 'H', 'LATIN CAPITAL LETTER H');
    add(0x25CF, 'H18533', 'BLACK CIRCLE');
    add(0x25AA, 'H18543', 'BLACK SMALL SQUARE');
    add(0x25AB, 'H18551', 'WHITE SMALL SQUARE');
    add(0x25A1, 'H22073', 'WHITE SQUARE');
    add(0x0126, 'Hbar', 'LATIN CAPITAL LETTER H WITH STROKE');
    add(0x0124, 'Hcircumflex', 'LATIN CAPITAL LETTER H WITH CIRCUMFLEX');
    add(0x0049, 'I', 'LATIN CAPITAL LETTER I');
    add(0x0132, 'IJ', 'LATIN CAPITAL LIGATURE IJ');
    add(0x00CD, 'Iacute', 'LATIN CAPITAL LETTER I WITH ACUTE');
    add(0x012C, 'Ibreve', 'LATIN CAPITAL LETTER I WITH BREVE');
    add(0x00CE, 'Icircumflex', 'LATIN CAPITAL LETTER I WITH CIRCUMFLEX');
    add(0x00CF, 'Idieresis', 'LATIN CAPITAL LETTER I WITH DIAERESIS');
    add(0x0130, 'Idotaccent', 'LATIN CAPITAL LETTER I WITH DOT ABOVE');
    add(0x2111, 'Ifraktur', 'BLACK-LETTER CAPITAL I');
    add(0x00CC, 'Igrave', 'LATIN CAPITAL LETTER I WITH GRAVE');
    add(0x012A, 'Imacron', 'LATIN CAPITAL LETTER I WITH MACRON');
    add(0x012E, 'Iogonek', 'LATIN CAPITAL LETTER I WITH OGONEK');
    add(0x0399, 'Iota', 'GREEK CAPITAL LETTER IOTA');
    add(0x03AA, 'Iotadieresis', 'GREEK CAPITAL LETTER IOTA WITH DIALYTIKA');
    add(0x038A, 'Iotatonos', 'GREEK CAPITAL LETTER IOTA WITH TONOS');
    add(0x0128, 'Itilde', 'LATIN CAPITAL LETTER I WITH TILDE');
    add(0x004A, 'J', 'LATIN CAPITAL LETTER J');
    add(0x0134, 'Jcircumflex', 'LATIN CAPITAL LETTER J WITH CIRCUMFLEX');
    add(0x004B, 'K', 'LATIN CAPITAL LETTER K');
    add(0x039A, 'Kappa', 'GREEK CAPITAL LETTER KAPPA');
    add(0x004C, 'L', 'LATIN CAPITAL LETTER L');
    add(0x0139, 'Lacute', 'LATIN CAPITAL LETTER L WITH ACUTE');
    add(0x039B, 'Lambda', 'GREEK CAPITAL LETTER LAMDA');
    add(0x013D, 'Lcaron', 'LATIN CAPITAL LETTER L WITH CARON');
    add(0x013F, 'Ldot', 'LATIN CAPITAL LETTER L WITH MIDDLE DOT');
    add(0x0141, 'Lslash', 'LATIN CAPITAL LETTER L WITH STROKE');
    add(0x004D, 'M', 'LATIN CAPITAL LETTER M');
    add(0x039C, 'Mu', 'GREEK CAPITAL LETTER MU');
    add(0x004E, 'N', 'LATIN CAPITAL LETTER N');
    add(0x0143, 'Nacute', 'LATIN CAPITAL LETTER N WITH ACUTE');
    add(0x0147, 'Ncaron', 'LATIN CAPITAL LETTER N WITH CARON');
    add(0x00D1, 'Ntilde', 'LATIN CAPITAL LETTER N WITH TILDE');
    add(0x039D, 'Nu', 'GREEK CAPITAL LETTER NU');
    add(0x004F, 'O', 'LATIN CAPITAL LETTER O');
    add(0x0152, 'OE', 'LATIN CAPITAL LIGATURE OE');
    add(0x00D3, 'Oacute', 'LATIN CAPITAL LETTER O WITH ACUTE');
    add(0x014E, 'Obreve', 'LATIN CAPITAL LETTER O WITH BREVE');
    add(0x00D4, 'Ocircumflex', 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX');
    add(0x00D6, 'Odieresis', 'LATIN CAPITAL LETTER O WITH DIAERESIS');
    add(0x00D2, 'Ograve', 'LATIN CAPITAL LETTER O WITH GRAVE');
    add(0x01A0, 'Ohorn', 'LATIN CAPITAL LETTER O WITH HORN');
    add(0x0150, 'Ohungarumlaut', 'LATIN CAPITAL LETTER O WITH DOUBLE ACUTE');
    add(0x014C, 'Omacron', 'LATIN CAPITAL LETTER O WITH MACRON');
    add(0x2126, 'Omega', 'OHM SIGN');
    add(0x038F, 'Omegatonos', 'GREEK CAPITAL LETTER OMEGA WITH TONOS');
    add(0x039F, 'Omicron', 'GREEK CAPITAL LETTER OMICRON');
    add(0x038C, 'Omicrontonos', 'GREEK CAPITAL LETTER OMICRON WITH TONOS');
    add(0x00D8, 'Oslash', 'LATIN CAPITAL LETTER O WITH STROKE');
    add(0x01FE, 'Oslashacute', 'LATIN CAPITAL LETTER O WITH STROKE AND ACUTE');
    add(0x00D5, 'Otilde', 'LATIN CAPITAL LETTER O WITH TILDE');
    add(0x0050, 'P', 'LATIN CAPITAL LETTER P');
    add(0x03A6, 'Phi', 'GREEK CAPITAL LETTER PHI');
    add(0x03A0, 'Pi', 'GREEK CAPITAL LETTER PI');
    add(0x03A8, 'Psi', 'GREEK CAPITAL LETTER PSI');
    add(0x0051, 'Q', 'LATIN CAPITAL LETTER Q');
    add(0x0052, 'R', 'LATIN CAPITAL LETTER R');
    add(0x0154, 'Racute', 'LATIN CAPITAL LETTER R WITH ACUTE');
    add(0x0158, 'Rcaron', 'LATIN CAPITAL LETTER R WITH CARON');
    add(0x211C, 'Rfraktur', 'BLACK-LETTER CAPITAL R');
    add(0x03A1, 'Rho', 'GREEK CAPITAL LETTER RHO');
    add(0x0053, 'S', 'LATIN CAPITAL LETTER S');
    add(0x250C, 'SF010000', 'BOX DRAWINGS LIGHT DOWN AND RIGHT');
    add(0x2514, 'SF020000', 'BOX DRAWINGS LIGHT UP AND RIGHT');
    add(0x2510, 'SF030000', 'BOX DRAWINGS LIGHT DOWN AND LEFT');
    add(0x2518, 'SF040000', 'BOX DRAWINGS LIGHT UP AND LEFT');
    add(0x253C, 'SF050000', 'BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL');
    add(0x252C, 'SF060000', 'BOX DRAWINGS LIGHT DOWN AND HORIZONTAL');
    add(0x2534, 'SF070000', 'BOX DRAWINGS LIGHT UP AND HORIZONTAL');
    add(0x251C, 'SF080000', 'BOX DRAWINGS LIGHT VERTICAL AND RIGHT');
    add(0x2524, 'SF090000', 'BOX DRAWINGS LIGHT VERTICAL AND LEFT');
    add(0x2500, 'SF100000', 'BOX DRAWINGS LIGHT HORIZONTAL');
    add(0x2502, 'SF110000', 'BOX DRAWINGS LIGHT VERTICAL');
    add(0x2561, 'SF190000', 'BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE');
    add(0x2562, 'SF200000', 'BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE');
    add(0x2556, 'SF210000', 'BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE');
    add(0x2555, 'SF220000', 'BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE');
    add(0x2563, 'SF230000', 'BOX DRAWINGS DOUBLE VERTICAL AND LEFT');
    add(0x2551, 'SF240000', 'BOX DRAWINGS DOUBLE VERTICAL');
    add(0x2557, 'SF250000', 'BOX DRAWINGS DOUBLE DOWN AND LEFT');
    add(0x255D, 'SF260000', 'BOX DRAWINGS DOUBLE UP AND LEFT');
    add(0x255C, 'SF270000', 'BOX DRAWINGS UP DOUBLE AND LEFT SINGLE');
    add(0x255B, 'SF280000', 'BOX DRAWINGS UP SINGLE AND LEFT DOUBLE');
    add(0x255E, 'SF360000', 'BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE');
    add(0x255F, 'SF370000', 'BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE');
    add(0x255A, 'SF380000', 'BOX DRAWINGS DOUBLE UP AND RIGHT');
    add(0x2554, 'SF390000', 'BOX DRAWINGS DOUBLE DOWN AND RIGHT');
    add(0x2569, 'SF400000', 'BOX DRAWINGS DOUBLE UP AND HORIZONTAL');
    add(0x2566, 'SF410000', 'BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL');
    add(0x2560, 'SF420000', 'BOX DRAWINGS DOUBLE VERTICAL AND RIGHT');
    add(0x2550, 'SF430000', 'BOX DRAWINGS DOUBLE HORIZONTAL');
    add(0x256C, 'SF440000', 'BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL');
    add(0x2567, 'SF450000', 'BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE');
    add(0x2568, 'SF460000', 'BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE');
    add(0x2564, 'SF470000', 'BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE');
    add(0x2565, 'SF480000', 'BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE');
    add(0x2559, 'SF490000', 'BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE');
    add(0x2558, 'SF500000', 'BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE');
    add(0x2552, 'SF510000', 'BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE');
    add(0x2553, 'SF520000', 'BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE');
    add(0x256B, 'SF530000', 'BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE');
    add(0x256A, 'SF540000', 'BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE');
    add(0x015A, 'Sacute', 'LATIN CAPITAL LETTER S WITH ACUTE');
    add(0x0160, 'Scaron', 'LATIN CAPITAL LETTER S WITH CARON');
    add(0x015E, 'Scedilla', 'LATIN CAPITAL LETTER S WITH CEDILLA');
    add(0x015C, 'Scircumflex', 'LATIN CAPITAL LETTER S WITH CIRCUMFLEX');
    add(0x03A3, 'Sigma', 'GREEK CAPITAL LETTER SIGMA');
    add(0x0054, 'T', 'LATIN CAPITAL LETTER T');
    add(0x03A4, 'Tau', 'GREEK CAPITAL LETTER TAU');
    add(0x0166, 'Tbar', 'LATIN CAPITAL LETTER T WITH STROKE');
    add(0x0164, 'Tcaron', 'LATIN CAPITAL LETTER T WITH CARON');
    add(0x0398, 'Theta', 'GREEK CAPITAL LETTER THETA');
    add(0x00DE, 'Thorn', 'LATIN CAPITAL LETTER THORN');
    add(0x0055, 'U', 'LATIN CAPITAL LETTER U');
    add(0x00DA, 'Uacute', 'LATIN CAPITAL LETTER U WITH ACUTE');
    add(0x016C, 'Ubreve', 'LATIN CAPITAL LETTER U WITH BREVE');
    add(0x00DB, 'Ucircumflex', 'LATIN CAPITAL LETTER U WITH CIRCUMFLEX');
    add(0x00DC, 'Udieresis', 'LATIN CAPITAL LETTER U WITH DIAERESIS');
    add(0x00D9, 'Ugrave', 'LATIN CAPITAL LETTER U WITH GRAVE');
    add(0x01AF, 'Uhorn', 'LATIN CAPITAL LETTER U WITH HORN');
    add(0x0170, 'Uhungarumlaut', 'LATIN CAPITAL LETTER U WITH DOUBLE ACUTE');
    add(0x016A, 'Umacron', 'LATIN CAPITAL LETTER U WITH MACRON');
    add(0x0172, 'Uogonek', 'LATIN CAPITAL LETTER U WITH OGONEK');
    add(0x03A5, 'Upsilon', 'GREEK CAPITAL LETTER UPSILON');
    add(0x03D2, 'Upsilon1', 'GREEK UPSILON WITH HOOK SYMBOL');
    add(0x03AB, 'Upsilondieresis', 'GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA');
    add(0x038E, 'Upsilontonos', 'GREEK CAPITAL LETTER UPSILON WITH TONOS');
    add(0x016E, 'Uring', 'LATIN CAPITAL LETTER U WITH RING ABOVE');
    add(0x0168, 'Utilde', 'LATIN CAPITAL LETTER U WITH TILDE');
    add(0x0056, 'V', 'LATIN CAPITAL LETTER V');
    add(0x0057, 'W', 'LATIN CAPITAL LETTER W');
    add(0x1E82, 'Wacute', 'LATIN CAPITAL LETTER W WITH ACUTE');
    add(0x0174, 'Wcircumflex', 'LATIN CAPITAL LETTER W WITH CIRCUMFLEX');
    add(0x1E84, 'Wdieresis', 'LATIN CAPITAL LETTER W WITH DIAERESIS');
    add(0x1E80, 'Wgrave', 'LATIN CAPITAL LETTER W WITH GRAVE');
    add(0x0058, 'X', 'LATIN CAPITAL LETTER X');
    add(0x039E, 'Xi', 'GREEK CAPITAL LETTER XI');
    add(0x0059, 'Y', 'LATIN CAPITAL LETTER Y');
    add(0x00DD, 'Yacute', 'LATIN CAPITAL LETTER Y WITH ACUTE');
    add(0x0176, 'Ycircumflex', 'LATIN CAPITAL LETTER Y WITH CIRCUMFLEX');
    add(0x0178, 'Ydieresis', 'LATIN CAPITAL LETTER Y WITH DIAERESIS');
    add(0x1EF2, 'Ygrave', 'LATIN CAPITAL LETTER Y WITH GRAVE');
    add(0x005A, 'Z', 'LATIN CAPITAL LETTER Z');
    add(0x0179, 'Zacute', 'LATIN CAPITAL LETTER Z WITH ACUTE');
    add(0x017D, 'Zcaron', 'LATIN CAPITAL LETTER Z WITH CARON');
    add(0x017B, 'Zdotaccent', 'LATIN CAPITAL LETTER Z WITH DOT ABOVE');
    add(0x0396, 'Zeta', 'GREEK CAPITAL LETTER ZETA');
    add(0x0061, 'a', 'LATIN SMALL LETTER A');
    add(0x00E1, 'aacute', 'LATIN SMALL LETTER A WITH ACUTE');
    add(0x0103, 'abreve', 'LATIN SMALL LETTER A WITH BREVE');
    add(0x00E2, 'acircumflex', 'LATIN SMALL LETTER A WITH CIRCUMFLEX');
    add(0x00B4, 'acute', 'ACUTE ACCENT');
    add(0x0301, 'acutecomb', 'COMBINING ACUTE ACCENT');
    add(0x00E4, 'adieresis', 'LATIN SMALL LETTER A WITH DIAERESIS');
    add(0x00E6, 'ae', 'LATIN SMALL LETTER AE');
    add(0x01FD, 'aeacute', 'LATIN SMALL LETTER AE WITH ACUTE');
    add(0x00E0, 'agrave', 'LATIN SMALL LETTER A WITH GRAVE');
    add(0x2135, 'aleph', 'ALEF SYMBOL');
    add(0x03B1, 'alpha', 'GREEK SMALL LETTER ALPHA');
    add(0x03AC, 'alphatonos', 'GREEK SMALL LETTER ALPHA WITH TONOS');
    add(0x0101, 'amacron', 'LATIN SMALL LETTER A WITH MACRON');
    add(0x0026, 'ampersand', 'AMPERSAND');
    add(0x2220, 'angle', 'ANGLE');
    add(0x2329, 'angleleft', 'LEFT-POINTING ANGLE BRACKET');
    add(0x232A, 'angleright', 'RIGHT-POINTING ANGLE BRACKET');
    add(0x0387, 'anoteleia', 'GREEK ANO TELEIA');
    add(0x0105, 'aogonek', 'LATIN SMALL LETTER A WITH OGONEK');
    add(0x2248, 'approxequal', 'ALMOST EQUAL TO');
    add(0x00E5, 'aring', 'LATIN SMALL LETTER A WITH RING ABOVE');
    add(0x01FB, 'aringacute', 'LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE');
    add(0x2194, 'arrowboth', 'LEFT RIGHT ARROW');
    add(0x21D4, 'arrowdblboth', 'LEFT RIGHT DOUBLE ARROW');
    add(0x21D3, 'arrowdbldown', 'DOWNWARDS DOUBLE ARROW');
    add(0x21D0, 'arrowdblleft', 'LEFTWARDS DOUBLE ARROW');
    add(0x21D2, 'arrowdblright', 'RIGHTWARDS DOUBLE ARROW');
    add(0x21D1, 'arrowdblup', 'UPWARDS DOUBLE ARROW');
    add(0x2193, 'arrowdown', 'DOWNWARDS ARROW');
    add(0x2190, 'arrowleft', 'LEFTWARDS ARROW');
    add(0x2192, 'arrowright', 'RIGHTWARDS ARROW');
    add(0x2191, 'arrowup', 'UPWARDS ARROW');
    add(0x2195, 'arrowupdn', 'UP DOWN ARROW');
    add(0x21A8, 'arrowupdnbse', 'UP DOWN ARROW WITH BASE');
    add(0x005E, 'asciicircum', 'CIRCUMFLEX ACCENT');
    add(0x007E, 'asciitilde', 'TILDE');
    add(0x002A, 'asterisk', 'ASTERISK');
    add(0x2217, 'asteriskmath', 'ASTERISK OPERATOR');
    add(0x0040, 'at', 'COMMERCIAL AT');
    add(0x00E3, 'atilde', 'LATIN SMALL LETTER A WITH TILDE');
    add(0x0062, 'b', 'LATIN SMALL LETTER B');
    add(0x005C, 'backslash', 'REVERSE SOLIDUS');
    add(0x007C, 'bar', 'VERTICAL LINE');
    add(0x03B2, 'beta', 'GREEK SMALL LETTER BETA');
    add(0x2588, 'block', 'FULL BLOCK');
    add(0x007B, 'braceleft', 'LEFT CURLY BRACKET');
    add(0x007D, 'braceright', 'RIGHT CURLY BRACKET');
    add(0x005B, 'bracketleft', 'LEFT SQUARE BRACKET');
    add(0x005D, 'bracketright', 'RIGHT SQUARE BRACKET');
    add(0x02D8, 'breve', 'BREVE');
    add(0x00A6, 'brokenbar', 'BROKEN BAR');
    add(0x2022, 'bullet', 'BULLET');
    add(0x0063, 'c', 'LATIN SMALL LETTER C');
    add(0x0107, 'cacute', 'LATIN SMALL LETTER C WITH ACUTE');
    add(0x02C7, 'caron', 'CARON');
    add(0x21B5, 'carriagereturn', 'DOWNWARDS ARROW WITH CORNER LEFTWARDS');
    add(0x010D, 'ccaron', 'LATIN SMALL LETTER C WITH CARON');
    add(0x00E7, 'ccedilla', 'LATIN SMALL LETTER C WITH CEDILLA');
    add(0x0109, 'ccircumflex', 'LATIN SMALL LETTER C WITH CIRCUMFLEX');
    add(0x010B, 'cdotaccent', 'LATIN SMALL LETTER C WITH DOT ABOVE');
    add(0x00B8, 'cedilla', 'CEDILLA');
    add(0x00A2, 'cent', 'CENT SIGN');
    add(0x03C7, 'chi', 'GREEK SMALL LETTER CHI');
    add(0x25CB, 'circle', 'WHITE CIRCLE');
    add(0x2297, 'circlemultiply', 'CIRCLED TIMES');
    add(0x2295, 'circleplus', 'CIRCLED PLUS');
    add(0x02C6, 'circumflex', 'MODIFIER LETTER CIRCUMFLEX ACCENT');
    add(0x2663, 'club', 'BLACK CLUB SUIT');
    add(0x003A, 'colon', 'COLON');
    add(0x20A1, 'colonmonetary', 'COLON SIGN');
    add(0x002C, 'comma', 'COMMA');
    add(0x2245, 'congruent', 'APPROXIMATELY EQUAL TO');
    add(0x00A9, 'copyright', 'COPYRIGHT SIGN');
    add(0x00A4, 'currency', 'CURRENCY SIGN');
    add(0x0064, 'd', 'LATIN SMALL LETTER D');
    add(0x2020, 'dagger', 'DAGGER');
    add(0x2021, 'daggerdbl', 'DOUBLE DAGGER');
    add(0x010F, 'dcaron', 'LATIN SMALL LETTER D WITH CARON');
    add(0x0111, 'dcroat', 'LATIN SMALL LETTER D WITH STROKE');
    add(0x00B0, 'degree', 'DEGREE SIGN');
    add(0x03B4, 'delta', 'GREEK SMALL LETTER DELTA');
    add(0x2666, 'diamond', 'BLACK DIAMOND SUIT');
    add(0x00A8, 'dieresis', 'DIAERESIS');
    add(0x0385, 'dieresistonos', 'GREEK DIALYTIKA TONOS');
    add(0x00F7, 'divide', 'DIVISION SIGN');
    add(0x2593, 'dkshade', 'DARK SHADE');
    add(0x2584, 'dnblock', 'LOWER HALF BLOCK');
    add(0x0024, 'dollar', 'DOLLAR SIGN');
    add(0x20AB, 'dong', 'DONG SIGN');
    add(0x02D9, 'dotaccent', 'DOT ABOVE');
    add(0x0323, 'dotbelowcomb', 'COMBINING DOT BELOW');
    add(0x0131, 'dotlessi', 'LATIN SMALL LETTER DOTLESS I');
    add(0x22C5, 'dotmath', 'DOT OPERATOR');
    add(0x0065, 'e', 'LATIN SMALL LETTER E');
    add(0x00E9, 'eacute', 'LATIN SMALL LETTER E WITH ACUTE');
    add(0x0115, 'ebreve', 'LATIN SMALL LETTER E WITH BREVE');
    add(0x011B, 'ecaron', 'LATIN SMALL LETTER E WITH CARON');
    add(0x00EA, 'ecircumflex', 'LATIN SMALL LETTER E WITH CIRCUMFLEX');
    add(0x00EB, 'edieresis', 'LATIN SMALL LETTER E WITH DIAERESIS');
    add(0x0117, 'edotaccent', 'LATIN SMALL LETTER E WITH DOT ABOVE');
    add(0x00E8, 'egrave', 'LATIN SMALL LETTER E WITH GRAVE');
    add(0x0038, 'eight', 'DIGIT EIGHT');
    add(0x2208, 'element', 'ELEMENT OF');
    add(0x2026, 'ellipsis', 'HORIZONTAL ELLIPSIS');
    add(0x0113, 'emacron', 'LATIN SMALL LETTER E WITH MACRON');
    add(0x2014, 'emdash', 'EM DASH');
    add(0x2205, 'emptyset', 'EMPTY SET');
    add(0x2013, 'endash', 'EN DASH');
    add(0x014B, 'eng', 'LATIN SMALL LETTER ENG');
    add(0x0119, 'eogonek', 'LATIN SMALL LETTER E WITH OGONEK');
    add(0x03B5, 'epsilon', 'GREEK SMALL LETTER EPSILON');
    add(0x03AD, 'epsilontonos', 'GREEK SMALL LETTER EPSILON WITH TONOS');
    add(0x003D, 'equal', 'EQUALS SIGN');
    add(0x2261, 'equivalence', 'IDENTICAL TO');
    add(0x212E, 'estimated', 'ESTIMATED SYMBOL');
    add(0x03B7, 'eta', 'GREEK SMALL LETTER ETA');
    add(0x03AE, 'etatonos', 'GREEK SMALL LETTER ETA WITH TONOS');
    add(0x00F0, 'eth', 'LATIN SMALL LETTER ETH');
    add(0x0021, 'exclam', 'EXCLAMATION MARK');
    add(0x203C, 'exclamdbl', 'DOUBLE EXCLAMATION MARK');
    add(0x00A1, 'exclamdown', 'INVERTED EXCLAMATION MARK');
    add(0x2203, 'existential', 'THERE EXISTS');
    add(0x0066, 'f', 'LATIN SMALL LETTER F');
    add(0x2640, 'female', 'FEMALE SIGN');
    add(0x2012, 'figuredash', 'FIGURE DASH');
    add(0x25A0, 'filledbox', 'BLACK SQUARE');
    add(0x25AC, 'filledrect', 'BLACK RECTANGLE');
    add(0x0035, 'five', 'DIGIT FIVE');
    add(0x215D, 'fiveeighths', 'VULGAR FRACTION FIVE EIGHTHS');
    add(0x0192, 'florin', 'LATIN SMALL LETTER F WITH HOOK');
    add(0x0034, 'four', 'DIGIT FOUR');
    add(0x2044, 'fraction', 'FRACTION SLASH');
    add(0x20A3, 'franc', 'FRENCH FRANC SIGN');
    add(0x0067, 'g', 'LATIN SMALL LETTER G');
    add(0x03B3, 'gamma', 'GREEK SMALL LETTER GAMMA');
    add(0x011F, 'gbreve', 'LATIN SMALL LETTER G WITH BREVE');
    add(0x01E7, 'gcaron', 'LATIN SMALL LETTER G WITH CARON');
    add(0x011D, 'gcircumflex', 'LATIN SMALL LETTER G WITH CIRCUMFLEX');
    add(0x0121, 'gdotaccent', 'LATIN SMALL LETTER G WITH DOT ABOVE');
    add(0x00DF, 'germandbls', 'LATIN SMALL LETTER SHARP S');
    add(0x2207, 'gradient', 'NABLA');
    add(0x0060, 'grave', 'GRAVE ACCENT');
    add(0x0300, 'gravecomb', 'COMBINING GRAVE ACCENT');
    add(0x003E, 'greater', 'GREATER-THAN SIGN');
    add(0x2265, 'greaterequal', 'GREATER-THAN OR EQUAL TO');
    add(0x00AB, 'guillemotleft', 'LEFT-POINTING DOUBLE ANGLE QUOTATION MARK');
    add(0x00BB, 'guillemotright', 'RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK');
    add(0x2039, 'guilsinglleft', 'SINGLE LEFT-POINTING ANGLE QUOTATION MARK');
    add(0x203A, 'guilsinglright', 'SINGLE RIGHT-POINTING ANGLE QUOTATION MARK');
    add(0x0068, 'h', 'LATIN SMALL LETTER H');
    add(0x0127, 'hbar', 'LATIN SMALL LETTER H WITH STROKE');
    add(0x0125, 'hcircumflex', 'LATIN SMALL LETTER H WITH CIRCUMFLEX');
    add(0x2665, 'heart', 'BLACK HEART SUIT');
    add(0x0309, 'hookabovecomb', 'COMBINING HOOK ABOVE');
    add(0x2302, 'house', 'HOUSE');
    add(0x02DD, 'hungarumlaut', 'DOUBLE ACUTE ACCENT');
    add(0x002D, 'hyphen', 'HYPHEN-MINUS');
    add(0x0069, 'i', 'LATIN SMALL LETTER I');
    add(0x00ED, 'iacute', 'LATIN SMALL LETTER I WITH ACUTE');
    add(0x012D, 'ibreve', 'LATIN SMALL LETTER I WITH BREVE');
    add(0x00EE, 'icircumflex', 'LATIN SMALL LETTER I WITH CIRCUMFLEX');
    add(0x00EF, 'idieresis', 'LATIN SMALL LETTER I WITH DIAERESIS');
    add(0x00EC, 'igrave', 'LATIN SMALL LETTER I WITH GRAVE');
    add(0x0133, 'ij', 'LATIN SMALL LIGATURE IJ');
    add(0x012B, 'imacron', 'LATIN SMALL LETTER I WITH MACRON');
    add(0x221E, 'infinity', 'INFINITY');
    add(0x222B, 'integral', 'INTEGRAL');
    add(0x2321, 'integralbt', 'BOTTOM HALF INTEGRAL');
    add(0x2320, 'integraltp', 'TOP HALF INTEGRAL');
    add(0x2229, 'intersection', 'INTERSECTION');
    add(0x25D8, 'invbullet', 'INVERSE BULLET');
    add(0x25D9, 'invcircle', 'INVERSE WHITE CIRCLE');
    add(0x263B, 'invsmileface', 'BLACK SMILING FACE');
    add(0x012F, 'iogonek', 'LATIN SMALL LETTER I WITH OGONEK');
    add(0x03B9, 'iota', 'GREEK SMALL LETTER IOTA');
    add(0x03CA, 'iotadieresis', 'GREEK SMALL LETTER IOTA WITH DIALYTIKA');
    add(0x0390, 'iotadieresistonos', 'GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS');
    add(0x03AF, 'iotatonos', 'GREEK SMALL LETTER IOTA WITH TONOS');
    add(0x0129, 'itilde', 'LATIN SMALL LETTER I WITH TILDE');
    add(0x006A, 'j', 'LATIN SMALL LETTER J');
    add(0x0135, 'jcircumflex', 'LATIN SMALL LETTER J WITH CIRCUMFLEX');
    add(0x006B, 'k', 'LATIN SMALL LETTER K');
    add(0x03BA, 'kappa', 'GREEK SMALL LETTER KAPPA');
    add(0x0138, 'kgreenlandic', 'LATIN SMALL LETTER KRA');
    add(0x006C, 'l', 'LATIN SMALL LETTER L');
    add(0x013A, 'lacute', 'LATIN SMALL LETTER L WITH ACUTE');
    add(0x03BB, 'lambda', 'GREEK SMALL LETTER LAMDA');
    add(0x013E, 'lcaron', 'LATIN SMALL LETTER L WITH CARON');
    add(0x0140, 'ldot', 'LATIN SMALL LETTER L WITH MIDDLE DOT');
    add(0x003C, 'less', 'LESS-THAN SIGN');
    add(0x2264, 'lessequal', 'LESS-THAN OR EQUAL TO');
    add(0x258C, 'lfblock', 'LEFT HALF BLOCK');
    add(0x20A4, 'lira', 'LIRA SIGN');
    add(0x2227, 'logicaland', 'LOGICAL AND');
    add(0x00AC, 'logicalnot', 'NOT SIGN');
    add(0x2228, 'logicalor', 'LOGICAL OR');
    add(0x017F, 'longs', 'LATIN SMALL LETTER LONG S');
    add(0x25CA, 'lozenge', 'LOZENGE');
    add(0x0142, 'lslash', 'LATIN SMALL LETTER L WITH STROKE');
    add(0x2591, 'ltshade', 'LIGHT SHADE');
    add(0x006D, 'm', 'LATIN SMALL LETTER M');
    add(0x00AF, 'macron', 'MACRON');
    add(0x2642, 'male', 'MALE SIGN');
    add(0x2212, 'minus', 'MINUS SIGN');
    add(0x2032, 'minute', 'PRIME');
    add(0x00B5, 'mu', 'MICRO SIGN');
    add(0x00D7, 'multiply', 'MULTIPLICATION SIGN');
    add(0x266A, 'musicalnote', 'EIGHTH NOTE');
    add(0x266B, 'musicalnotedbl', 'BEAMED EIGHTH NOTES');
    add(0x006E, 'n', 'LATIN SMALL LETTER N');
    add(0x0144, 'nacute', 'LATIN SMALL LETTER N WITH ACUTE');
    add(0x0149, 'napostrophe', 'LATIN SMALL LETTER N PRECEDED BY APOSTROPHE');
    add(0x0148, 'ncaron', 'LATIN SMALL LETTER N WITH CARON');
    add(0x0039, 'nine', 'DIGIT NINE');
    add(0x2209, 'notelement', 'NOT AN ELEMENT OF');
    add(0x2260, 'notequal', 'NOT EQUAL TO');
    add(0x2284, 'notsubset', 'NOT A SUBSET OF');
    add(0x00F1, 'ntilde', 'LATIN SMALL LETTER N WITH TILDE');
    add(0x03BD, 'nu', 'GREEK SMALL LETTER NU');
    add(0x0023, 'numbersign', 'NUMBER SIGN');
    add(0x006F, 'o', 'LATIN SMALL LETTER O');
    add(0x00F3, 'oacute', 'LATIN SMALL LETTER O WITH ACUTE');
    add(0x014F, 'obreve', 'LATIN SMALL LETTER O WITH BREVE');
    add(0x00F4, 'ocircumflex', 'LATIN SMALL LETTER O WITH CIRCUMFLEX');
    add(0x00F6, 'odieresis', 'LATIN SMALL LETTER O WITH DIAERESIS');
    add(0x0153, 'oe', 'LATIN SMALL LIGATURE OE');
    add(0x02DB, 'ogonek', 'OGONEK');
    add(0x00F2, 'ograve', 'LATIN SMALL LETTER O WITH GRAVE');
    add(0x01A1, 'ohorn', 'LATIN SMALL LETTER O WITH HORN');
    add(0x0151, 'ohungarumlaut', 'LATIN SMALL LETTER O WITH DOUBLE ACUTE');
    add(0x014D, 'omacron', 'LATIN SMALL LETTER O WITH MACRON');
    add(0x03C9, 'omega', 'GREEK SMALL LETTER OMEGA');
    add(0x03D6, 'omega1', 'GREEK PI SYMBOL');
    add(0x03CE, 'omegatonos', 'GREEK SMALL LETTER OMEGA WITH TONOS');
    add(0x03BF, 'omicron', 'GREEK SMALL LETTER OMICRON');
    add(0x03CC, 'omicrontonos', 'GREEK SMALL LETTER OMICRON WITH TONOS');
    add(0x0031, 'one', 'DIGIT ONE');
    add(0x2024, 'onedotenleader', 'ONE DOT LEADER');
    add(0x215B, 'oneeighth', 'VULGAR FRACTION ONE EIGHTH');
    add(0x00BD, 'onehalf', 'VULGAR FRACTION ONE HALF');
    add(0x00BC, 'onequarter', 'VULGAR FRACTION ONE QUARTER');
    add(0x2153, 'onethird', 'VULGAR FRACTION ONE THIRD');
    add(0x25E6, 'openbullet', 'WHITE BULLET');
    add(0x00AA, 'ordfeminine', 'FEMININE ORDINAL INDICATOR');
    add(0x00BA, 'ordmasculine', 'MASCULINE ORDINAL INDICATOR');
    add(0x221F, 'orthogonal', 'RIGHT ANGLE');
    add(0x00F8, 'oslash', 'LATIN SMALL LETTER O WITH STROKE');
    add(0x01FF, 'oslashacute', 'LATIN SMALL LETTER O WITH STROKE AND ACUTE');
    add(0x00F5, 'otilde', 'LATIN SMALL LETTER O WITH TILDE');
    add(0x0070, 'p', 'LATIN SMALL LETTER P');
    add(0x00B6, 'paragraph', 'PILCROW SIGN');
    add(0x0028, 'parenleft', 'LEFT PARENTHESIS');
    add(0x0029, 'parenright', 'RIGHT PARENTHESIS');
    add(0x2202, 'partialdiff', 'PARTIAL DIFFERENTIAL');
    add(0x0025, 'percent', 'PERCENT SIGN');
    add(0x002E, 'period', 'FULL STOP');
    add(0x00B7, 'periodcentered', 'MIDDLE DOT');
    add(0x22A5, 'perpendicular', 'UP TACK');
    add(0x2030, 'perthousand', 'PER MILLE SIGN');
    add(0x20A7, 'peseta', 'PESETA SIGN');
    add(0x03C6, 'phi', 'GREEK SMALL LETTER PHI');
    add(0x03D5, 'phi1', 'GREEK PHI SYMBOL');
    add(0x03C0, 'pi', 'GREEK SMALL LETTER PI');
    add(0x002B, 'plus', 'PLUS SIGN');
    add(0x00B1, 'plusminus', 'PLUS-MINUS SIGN');
    add(0x211E, 'prescription', 'PRESCRIPTION TAKE');
    add(0x220F, 'product', 'N-ARY PRODUCT');
    add(0x2282, 'propersubset', 'SUBSET OF');
    add(0x2283, 'propersuperset', 'SUPERSET OF');
    add(0x221D, 'proportional', 'PROPORTIONAL TO');
    add(0x03C8, 'psi', 'GREEK SMALL LETTER PSI');
    add(0x0071, 'q', 'LATIN SMALL LETTER Q');
    add(0x003F, 'question', 'QUESTION MARK');
    add(0x00BF, 'questiondown', 'INVERTED QUESTION MARK');
    add(0x0022, 'quotedbl', 'QUOTATION MARK');
    add(0x201E, 'quotedblbase', 'DOUBLE LOW-9 QUOTATION MARK');
    add(0x201C, 'quotedblleft', 'LEFT DOUBLE QUOTATION MARK');
    add(0x201D, 'quotedblright', 'RIGHT DOUBLE QUOTATION MARK');
    add(0x2018, 'quoteleft', 'LEFT SINGLE QUOTATION MARK');
    add(0x201B, 'quotereversed', 'SINGLE HIGH-REVERSED-9 QUOTATION MARK');
    add(0x2019, 'quoteright', 'RIGHT SINGLE QUOTATION MARK');
    add(0x201A, 'quotesinglbase', 'SINGLE LOW-9 QUOTATION MARK');
    add(0x0027, 'quotesingle', 'APOSTROPHE');
    add(0x0072, 'r', 'LATIN SMALL LETTER R');
    add(0x0155, 'racute', 'LATIN SMALL LETTER R WITH ACUTE');
    add(0x221A, 'radical', 'SQUARE ROOT');
    add(0x0159, 'rcaron', 'LATIN SMALL LETTER R WITH CARON');
    add(0x2286, 'reflexsubset', 'SUBSET OF OR EQUAL TO');
    add(0x2287, 'reflexsuperset', 'SUPERSET OF OR EQUAL TO');
    add(0x00AE, 'registered', 'REGISTERED SIGN');
    add(0x2310, 'revlogicalnot', 'REVERSED NOT SIGN');
    add(0x03C1, 'rho', 'GREEK SMALL LETTER RHO');
    add(0x02DA, 'ring', 'RING ABOVE');
    add(0x2590, 'rtblock', 'RIGHT HALF BLOCK');
    add(0x0073, 's', 'LATIN SMALL LETTER S');
    add(0x015B, 'sacute', 'LATIN SMALL LETTER S WITH ACUTE');
    add(0x0161, 'scaron', 'LATIN SMALL LETTER S WITH CARON');
    add(0x015F, 'scedilla', 'LATIN SMALL LETTER S WITH CEDILLA');
    add(0x015D, 'scircumflex', 'LATIN SMALL LETTER S WITH CIRCUMFLEX');
    add(0x2033, 'second', 'DOUBLE PRIME');
    add(0x00A7, 'section', 'SECTION SIGN');
    add(0x003B, 'semicolon', 'SEMICOLON');
    add(0x0037, 'seven', 'DIGIT SEVEN');
    add(0x215E, 'seveneighths', 'VULGAR FRACTION SEVEN EIGHTHS');
    add(0x2592, 'shade', 'MEDIUM SHADE');
    add(0x03C3, 'sigma', 'GREEK SMALL LETTER SIGMA');
    add(0x03C2, 'sigma1', 'GREEK SMALL LETTER FINAL SIGMA');
    add(0x223C, 'similar', 'TILDE OPERATOR');
    add(0x0036, 'six', 'DIGIT SIX');
    add(0x002F, 'slash', 'SOLIDUS');
    add(0x263A, 'smileface', 'WHITE SMILING FACE');
    add(0x0020, 'space', 'SPACE');
    add(0x2660, 'spade', 'BLACK SPADE SUIT');
    add(0x00A3, 'sterling', 'POUND SIGN');
    add(0x220B, 'suchthat', 'CONTAINS AS MEMBER');
    add(0x2211, 'summation', 'N-ARY SUMMATION');
    add(0x263C, 'sun', 'WHITE SUN WITH RAYS');
    add(0x0074, 't', 'LATIN SMALL LETTER T');
    add(0x03C4, 'tau', 'GREEK SMALL LETTER TAU');
    add(0x0167, 'tbar', 'LATIN SMALL LETTER T WITH STROKE');
    add(0x0165, 'tcaron', 'LATIN SMALL LETTER T WITH CARON');
    add(0x2234, 'therefore', 'THEREFORE');
    add(0x03B8, 'theta', 'GREEK SMALL LETTER THETA');
    add(0x03D1, 'theta1', 'GREEK THETA SYMBOL');
    add(0x00FE, 'thorn', 'LATIN SMALL LETTER THORN');
    add(0x0033, 'three', 'DIGIT THREE');
    add(0x215C, 'threeeighths', 'VULGAR FRACTION THREE EIGHTHS');
    add(0x00BE, 'threequarters', 'VULGAR FRACTION THREE QUARTERS');
    add(0x02DC, 'tilde', 'SMALL TILDE');
    add(0x0303, 'tildecomb', 'COMBINING TILDE');
    add(0x0384, 'tonos', 'GREEK TONOS');
    add(0x2122, 'trademark', 'TRADE MARK SIGN');
    add(0x25BC, 'triagdn', 'BLACK DOWN-POINTING TRIANGLE');
    add(0x25C4, 'triaglf', 'BLACK LEFT-POINTING POINTER');
    add(0x25BA, 'triagrt', 'BLACK RIGHT-POINTING POINTER');
    add(0x25B2, 'triagup', 'BLACK UP-POINTING TRIANGLE');
    add(0x0032, 'two', 'DIGIT TWO');
    add(0x2025, 'twodotenleader', 'TWO DOT LEADER');
    add(0x2154, 'twothirds', 'VULGAR FRACTION TWO THIRDS');
    add(0x0075, 'u', 'LATIN SMALL LETTER U');
    add(0x00FA, 'uacute', 'LATIN SMALL LETTER U WITH ACUTE');
    add(0x016D, 'ubreve', 'LATIN SMALL LETTER U WITH BREVE');
    add(0x00FB, 'ucircumflex', 'LATIN SMALL LETTER U WITH CIRCUMFLEX');
    add(0x00FC, 'udieresis', 'LATIN SMALL LETTER U WITH DIAERESIS');
    add(0x00F9, 'ugrave', 'LATIN SMALL LETTER U WITH GRAVE');
    add(0x01B0, 'uhorn', 'LATIN SMALL LETTER U WITH HORN');
    add(0x0171, 'uhungarumlaut', 'LATIN SMALL LETTER U WITH DOUBLE ACUTE');
    add(0x016B, 'umacron', 'LATIN SMALL LETTER U WITH MACRON');
    add(0x005F, 'underscore', 'LOW LINE');
    add(0x2017, 'underscoredbl', 'DOUBLE LOW LINE');
    add(0x222A, 'union', 'UNION');
    add(0x2200, 'universal', 'FOR ALL');
    add(0x0173, 'uogonek', 'LATIN SMALL LETTER U WITH OGONEK');
    add(0x2580, 'upblock', 'UPPER HALF BLOCK');
    add(0x03C5, 'upsilon', 'GREEK SMALL LETTER UPSILON');
    add(0x03CB, 'upsilondieresis', 'GREEK SMALL LETTER UPSILON WITH DIALYTIKA');
    add(0x03B0, 'upsilondieresistonos', 'GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS');
    add(0x03CD, 'upsilontonos', 'GREEK SMALL LETTER UPSILON WITH TONOS');
    add(0x016F, 'uring', 'LATIN SMALL LETTER U WITH RING ABOVE');
    add(0x0169, 'utilde', 'LATIN SMALL LETTER U WITH TILDE');
    add(0x0076, 'v', 'LATIN SMALL LETTER V');
    add(0x0077, 'w', 'LATIN SMALL LETTER W');
    add(0x1E83, 'wacute', 'LATIN SMALL LETTER W WITH ACUTE');
    add(0x0175, 'wcircumflex', 'LATIN SMALL LETTER W WITH CIRCUMFLEX');
    add(0x1E85, 'wdieresis', 'LATIN SMALL LETTER W WITH DIAERESIS');
    add(0x2118, 'weierstrass', 'SCRIPT CAPITAL P');
    add(0x1E81, 'wgrave', 'LATIN SMALL LETTER W WITH GRAVE');
    add(0x0078, 'x', 'LATIN SMALL LETTER X');
    add(0x03BE, 'xi', 'GREEK SMALL LETTER XI');
    add(0x0079, 'y', 'LATIN SMALL LETTER Y');
    add(0x00FD, 'yacute', 'LATIN SMALL LETTER Y WITH ACUTE');
    add(0x0177, 'ycircumflex', 'LATIN SMALL LETTER Y WITH CIRCUMFLEX');
    add(0x00FF, 'ydieresis', 'LATIN SMALL LETTER Y WITH DIAERESIS');
    add(0x00A5, 'yen', 'YEN SIGN');
    add(0x1EF3, 'ygrave', 'LATIN SMALL LETTER Y WITH GRAVE');
    add(0x007A, 'z', 'LATIN SMALL LETTER Z');
    add(0x017A, 'zacute', 'LATIN SMALL LETTER Z WITH ACUTE');
    add(0x017E, 'zcaron', 'LATIN SMALL LETTER Z WITH CARON');
    add(0x017C, 'zdotaccent', 'LATIN SMALL LETTER Z WITH DOT ABOVE');
    add(0x0030, 'zero', 'DIGIT ZERO');
    add(0x03B6, 'zeta', 'GREEK SMALL LETTER ZETA');
}

# or: uni%04X

sub add {
    my ($codepoint, $name, $unicodeName) = @_;
    push(@{$aglfnByNameArray{$name}}, $codepoint);
    push(@{$aglfnByCodepointArray{$codepoint}}, $name);
    $aglfnByName{$name} = $codepoint;
    $aglfnByCodepoint{$codepoint} = $name;
}

sub verify {
    foreach my $name (keys %aglfnByNameArray) {
	my $count = scalar @{$aglfnByNameArray{$name}};
	if ($count != 1) {
	    warn("$name => $count\n");
	}
    }
    foreach my $codepoint (keys %aglfnByCodepointArray) {
	my $count = scalar @{$aglfnByCodepointArray{$codepoint}};
	my $uplus = sprintf('U+%04X', $codepoint);
	if ($count != 1) {
	    warn("$uplus => $count\n");
	}
    }
}

sub adobeGlyphName {
    my ($codepoint) = @_;
    my $name = $aglfnByCodepoint{$codepoint};
    return $name if defined $name;
    return sprintf('uni%04X', $codepoint);
}

sub adobeGlyphCodepoint {
    my ($name) = @_;
    my $codepoint = $aglfnByName{$name};
    return $codepoint if defined $codepoint;
}

1;
